### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by sandonov** [ArjenSchwarz/packer_cleaner#1]
Hi,
I've setup your Lambda function and it is running per schedule but not sending notification or stopping, terminating packer instances. I have left one Packer builder intentionally running and has the `packer*random` key pair but for some reason the function does not work and I am unable to find out why. Logs are also not very helpful.

Thanks

**Comment by ArjenSchwarz** [comment]
Hi @sandonov,

Thanks for reporting this. Apologies if any of the below questions are obvious to you, I just want to rule out anything that might be causing your errors.

Can you tell me how you installed it? Did you use the Serverless Application Repository or do it directly?
Did you configure the SNS topic afterwards to ensure it sends emails to you?
What did you set the MaxPackerRuntime and RunFrequency parameters to?
And how long after starting the packer instance did you check if it had been detected?
Do the logs show the instance as running too long?

If I give you a version with more logging enabled, will you be willing to test it in your environment?

Thank you

**Comment by sandonov** [comment]
Hello @ArjenSchwarz,
Thanks for the quick reply. Let me give you the answers. 
 
> Did you use the Serverless Application Repository or do it directly?

Yes

> Did you configure the SNS topic afterwards to ensure it sends emails to you?

Yes

> What did you set the MaxPackerRuntime and RunFrequency parameters to?

MaxPackerRuntime - 2 , RunFrequency - never change the value, and checked runs once per hour.

> And how long after starting the packer instance did you check if it had been detected?

Basically I had a packer instance running all day, but was never detected by the function. I've started the packer build and left the EC2 instance running intentionally.

> Do the logs show the instance as running too long?

In the CW logs I only see the `START` , `END` , `REPORT` and the `VERSION` - $Latest  and of course the request ID is there but nothing else.

> If I give you a version with more logging enabled, will you be willing to test it in your environment?

I can do that

Thanks

**Comment by ArjenSchwarz** [comment]
Thanks for the answers. All of that should work, I've created a debug version that prints a lot of additional information but leaves the logic intact.

You can find the code at https://github.com/ArjenSchwarz/packer_cleaner/blob/debug/code/index.py

The easiest way to install this is to copy that code and replace the existing index.py file in the Lambda function that was created when you installed it from the SAR. Then it's simply a matter of running the Lambda function. This should happen automatically of course, but otherwise you can run a test event from the Lambda console (just the hello world one is fine, the function doesn't read any input). Even if the instance hasn't been running for long yet, it should already give output.

None of which it prints should be sensitive data, but please verify that before you share it with me.

Also, if it fails again, please share as much of the instance information as you're happy to. In particular I would like to know the name of assigned key, whether it's a Linux or Windows instance, if it's running in a private or public subnet, and what the instance state is when you run it.

In addition, I forgot to ask, but I assume the Lambda function is running in the same region as the instance?

**Comment by sandonov** [comment]
Okay,
I've updated the function and ran the test. Currently I have a packer instance running with the following details:
- Windows instance (last week was Linux)
- Private subnet
- State - `running`
- Name tag -  `Packer Builder`
- Private key - `packer_****-****-****-****-************`

and the result after running the test is:
```
START RequestId: **** Version: $LATEST
Starting the run
0 matching instances found
No instances found that were running too long
END RequestId: ****
REPORT RequestId: ****	Duration: 365.60 ms	Billed Duration: 400 ms 	Memory Size: 128 MB	Max Memory Used: 45 MB

**Comment by sandonov** [comment]
I just looked at your code in detail and found this:

```
Filters=[
                {
                    'Name': 'key-name',
                    'Values': [
                        'packer *'
                    ]
                },
```
You have a space between `packer` and the asterisk. After removing the space `packer*` I've got the result:


```
Starting the run
Found a reservation
Found an instance
Getting the calculated date
2018-05-07 11:29:32.899935+00:00
Getting the launchtime
2018-05-07 11:49:40+00:00
1 matching instances found
No instances found that were running too long

Hope this helps :)

**Comment by ArjenSchwarz** [comment]
Interesting, every time I tested it there was a space in the keyname. I wonder when that was changed. Anyway, I’ll deploy an update tomorrow to make it work (yes, just removing the space probably). 

Thank you again for reporting and then finding the problem.

**Comment by ArjenSchwarz** [comment]
A new version (1.0.5) has been released on the SAR that fixes this, and you should be able to upgrade to it by going to the application in the SAR at https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:613864977396:applications~Packer-Cleaner and deploying it again.
